### PR TITLE
Feature/file renderer

### PR DESCRIPTION
**Pull request by dwdmarkowski**

### CODE REVIEW

**Comment by PChmiel** [comment]
shouldn't we use some kind of abstraction over the stencil library?

**Comment by dwdmarkowski** [comment]
> shouldn't we use some kind of abstraction over the stencil library?

I'm not sure to be honest :) I started as you said but in the end I had just typical proxy which gave us nothing but boilerplate because it's just invocation of one method. Stencil's interface seems ok for us for now and I had feeling that this abstraction is redundant. I created our own protocol which is automatically conformed by stencil's implementation so we keep testability. Do you think it makes sense? :)

**Comment by PChmiel** [comment]
Hm, for me the profit is to have only one place related with external dependency, which makes it easy to replace or remove in case of changing mind. The question is should we do that in this project? @Vyeczorny what do you think?

**Comment by dwdmarkowski** [comment]
To replace this implementation we would have to implement our own template engine :) I thought it's unlikely to happen :D but ofc I can extract our proxy and it will be replacable, no problem, it's up to you guys

**Comment by Vyeczorny** [comment]
I would start as simple as possible. If Stencil's methods are good for us, I would leave it as is. I would introduce only two changes:

- right now, Stencil is imported in `Application` class, I think it should be removed from here
- I would move protocol back to `Application`, it's much easier to read `Application` class where every protocols are in the same place

**Pull request merged**
